name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - altair=5.5.0
  - annotated-types=0.7.0
  - anyio=4.6.2.post1
  - attrs=24.2.0
  - blinker=1.9.0
  - cachetools=5.5.0
  - certifi=2024.8.30
  - charset-normalizer=3.4.0
  - click=8.1.7
  - distro=1.9.0
  - faiss-cpu=1.9.0.post1
  - filelock=3.16.1
  - fsspec=2024.10.0
  - gitdb=4.0.11
  - gitpython=3.1.43
  - h11=0.14.0
  - httpcore=1.0.7
  - httpx=0.27.2
  - huggingface-hub=0.26.2
  - idna=3.10
  - jinja2=3.1.4
  - jiter=0.7.1
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - lxml=5.3.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - mpmath=1.3.0
  - narwhals=1.14.2
  - networkx=3.4.2
  - numpy=2.1.3
  - openai=1.55.0
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.0.0
  - protobuf=5.28.3
  - pyarrow=18.0.0
  - pydantic=2.10.1
  - pydantic-core=2.27.1
  - pydeck=0.9.1
  - pygments=2.18.0
  - pypdf2=3.0.1
  - python-dateutil=2.9.0.post0
  - python-docx=1.1.2
  - pytz=2024.2
  - pyyaml=6.0.2
  - referencing=0.35.1
  - regex=2024.11.6
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.21.0
  - safetensors=0.4.5
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - sentence-transformers=3.3.1
  - six=1.16.0
  - smmap=5.0.1
  - sniffio=1.3.1
  - streamlit=1.40.1
  - sympy=1.13.3
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tokenizers=0.20.3
  - toml=0.10.2
  - torch=2.2.2
  - tornado=6.4.2
  - tqdm=4.67.0
  - transformers=4.46.3
  - typing-extensions=4.12.2
  - tzdata=2024.2
  - urllib3=2.2.3
  - pip:
    - altair==5.5.0
    - annotated-types==0.7.0
    - anyio==4.6.2.post1
    - attrs==24.2.0
    - blinker==1.9.0
    - cachetools==5.5.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - distro==1.9.0
    - faiss-cpu==1.9.0.post1
    - filelock==3.16.1
    - fsspec==2024.10.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.27.2
    - huggingface-hub==0.26.2
    - idna==3.10
    - jinja2==3.1.4
    - jiter==0.7.1
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - lxml==5.3.0
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - mdurl==0.1.2
    - mpmath==1.3.0
    - narwhals==1.14.2
    - networkx==3.4.2
    - numpy==2.1.3
    - openai==1.55.0
    - packaging==24.2
    - pandas==2.2.3
    - pillow==11.0.0
    - protobuf==5.28.3
    - pyarrow==18.0.0
    - pydantic==2.10.1
    - pydantic-core==2.27.1
    - pydeck==0.9.1
    - pygments==2.18.0
    - pypdf2==3.0.1
    - python-dateutil==2.9.0.post0
    - python-docx==1.1.2
    - pytz==2024.2
    - pyyaml==6.0.2
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - rpds-py==0.21.0
    - safetensors==0.4.5
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sentence-transformers==3.3.1
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - streamlit==1.40.1
    - sympy==1.13.3
    - tenacity==9.0.0
    - threadpoolctl==3.5.0
    - tokenizers==0.20.3
    - toml==0.10.2
    - torch==2.2.2
    - tornado==6.4.2
    - tqdm==4.67.0
    - transformers==4.46.3
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3